function [SELE, Sp] = compute_sele_curve(p0, D, S, tau, alpha_scale, ...
    x, wavelength_PL, E_sorted, sort_idx, NC, NV, Kb, TK, C_auger, B0, ...
    n_k_wavelength, n_w_drude, k_w_drude, k_no_drude)

dEg = ( ...
    9.71  * (p0/1e18)^(1/3) + ...
    12.19 * (p0/1e18)^(1/4) + ...
    3.88  * (p0/1e18)^(1/2) ) / 1000;

Eg = 1.519 ...
   - 5.405e-4 * TK^2 / (TK + 204) ...
   - 0.8 * dEg;

ni = sqrt(NC * NV) * exp(-Eg / (2 * Kb * TK));

tau_auger = 1 / (p0^2 * C_auger);
tau_rad   = 1 / (p0 * B0);
tau_eff   = 1 / (1/tau + 1/tau_rad + 1/tau_auger);

% At lower doping the FCA drops
k_eff = k_no_drude + (k_w_drude - k_no_drude) * (p0 / 1e19);

Sp = calc_Sp2( ...
    x, wavelength_PL, p0, ni, tau_eff, S, D, ...
    n_k_wavelength, n_w_drude, k_eff, k_no_drude, ...
    alpha_scale);

SELE = trapz(E_sorted, Sp(sort_idx, :), 1);

end
